table stores
	lineageTag: dddc42ac-6e0c-4d1c-95fc-1c6940797f68

	measure oldest_store_open_date = MIN(stores[store_open_date])
		formatString: General Date
		lineageTag: 9b34736c-a6a6-4a93-bd6d-cf2fd0c7b236

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: f7962112-73e8-4d24-991c-336a47792ad7
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column store_name
		dataType: string
		lineageTag: 204b94b3-8d5f-47e7-9380-b6b518bd90a4
		summarizeBy: none
		sourceColumn: store_name

		annotation SummarizationSetBy = Automatic

	column store_type
		dataType: string
		lineageTag: bd79dbf0-48f5-4725-a425-bc6f24f24164
		summarizeBy: none
		sourceColumn: store_type

		annotation SummarizationSetBy = Automatic

	column store_open_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c77b509e-0fca-4d1d-81cb-8e464148b8a9
		summarizeBy: none
		sourceColumn: store_open_date

		variation Variation
			isDefault
			relationship: 66fac90e-b212-4a0a-8012-d3648b99ff35
			defaultHierarchy: LocalDateTable_f96cbe96-e72e-4472-90c0-3d743f3e47b3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column store_location
		dataType: string
		lineageTag: c81e89d7-5134-4638-afee-9cff051d6da7
		summarizeBy: none
		sourceColumn: store_location

		annotation SummarizationSetBy = Automatic

	partition stores = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\AndrewOtt\Desktop\Dev\power-bi\stores.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"store_id", Int64.Type}, {"store_name", type text}, {"store_type", type text}, {"store_open_date", type date}, {"store_location", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

